name: 'Build Windows App'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Build the app
      run: npm run tauri:build

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
        if-no-files-found: warn

    - name: Upload Windows Portable
      uses: actions/upload-artifact@v4
      with:
        name: windows-portable
        path: src-tauri/target/release/*.exe
        if-no-files-found: warn 