name: 'Build macOS Release'

on:
  # 推送到main分支时触发，或创建tag时触发
  push:
    branches: [ main ]
    tags:
      - 'v*'
  # 手动触发
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin,x86_64-apple-darwin

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Build Intel app
      run: npm run tauri build -- --target x86_64-apple-darwin
      env:
        # 跳过 macOS 代码签名（用于测试构建）
        APPLE_SIGNING_IDENTITY: "-"
    
    - name: Build Apple Silicon app
      run: npm run tauri build -- --target aarch64-apple-darwin
      env:
        # 跳过 macOS 代码签名（用于测试构建）
        APPLE_SIGNING_IDENTITY: "-" 

    - name: Get app version
      run: |
        version=$(node -pe "require('./package.json').version")
        echo "APP_VERSION=$version" >> $GITHUB_ENV

    - name: List build outputs (debug)
      run: |
        echo "=== Checking build outputs ==="
        find src-tauri/target -type f -name "*.dmg" -o -name "*.app" | head -20
        echo "=== Intel build ==="
        ls -la src-tauri/target/x86_64-apple-darwin/release/bundle/ || true
        echo "=== Apple Silicon build ==="
        ls -la src-tauri/target/aarch64-apple-darwin/release/bundle/ || true

    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: "鼠标步数计数器 macOS v${{ env.APP_VERSION }}"
        files: |
          src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Intel DMG (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-dmg-${{ env.APP_VERSION }}
        path: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
        if-no-files-found: warn
        retention-days: 30
    
    - name: Upload Apple Silicon DMG (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64-dmg-${{ env.APP_VERSION }}
        path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
        if-no-files-found: warn
        retention-days: 30

    - name: Create Intel APP archive
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        if [ -d "src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Mouse Step Counter.app" ]; then
          cd src-tauri/target/x86_64-apple-darwin/release/bundle/macos
          tar -czf "Mouse-Step-Counter-intel-${{ env.APP_VERSION }}.app.tar.gz" "Mouse Step Counter.app"
        fi
        
    - name: Create Apple Silicon APP archive
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        if [ -d "src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Mouse Step Counter.app" ]; then
          cd src-tauri/target/aarch64-apple-darwin/release/bundle/macos
          tar -czf "Mouse-Step-Counter-arm64-${{ env.APP_VERSION }}.app.tar.gz" "Mouse Step Counter.app"
        fi

    - name: Upload Intel APP (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-app-${{ env.APP_VERSION }}
        path: src-tauri/target/x86_64-apple-darwin/release/bundle/macos/*.app.tar.gz
        if-no-files-found: warn
        retention-days: 30
        
    - name: Upload Apple Silicon APP (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64-app-${{ env.APP_VERSION }}
        path: src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app.tar.gz
        if-no-files-found: warn
        retention-days: 30 