name: 'Build macOS Release'

on:
  # 推送到main分支时触发，或创建tag时触发
  push:
    branches: [ main ]
    tags:
      - 'v*'
  # 手动触发
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin,x86_64-apple-darwin

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Build the app
      run: npm run tauri:build
      env:
        # 跳过 macOS 代码签名（用于测试构建）
        APPLE_SIGNING_IDENTITY: "-"
        # 构建 Universal Binary（支持 Intel 和 Apple Silicon）
        TAURI_BUNDLE_MACOS_TARGETS: "universal-apple-darwin" 

    - name: Get app version
      run: |
        version=$(node -pe "require('./package.json').version")
        echo "APP_VERSION=$version" >> $GITHUB_ENV

    - name: List build outputs (debug)
      run: |
        echo "=== Checking build outputs ==="
        find src-tauri/target/release/bundle -type f -name "*.dmg" -o -name "*.app" | head -10
        ls -la src-tauri/target/release/bundle/ || true

    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: "鼠标步数计数器 macOS v${{ env.APP_VERSION }}"
        files: |
          src-tauri/target/release/bundle/dmg/*.dmg
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS DMG (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg-${{ env.APP_VERSION }}
        path: src-tauri/target/release/bundle/dmg/*.dmg
        if-no-files-found: warn
        retention-days: 30

    - name: Create APP archive
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        cd src-tauri/target/release/bundle/macos
        if [ -d "Mouse Step Counter.app" ]; then
          tar -czf "Mouse-Step-Counter-${{ env.APP_VERSION }}.app.tar.gz" "Mouse Step Counter.app"
        fi

    - name: Upload macOS APP (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-app-${{ env.APP_VERSION }}
        path: src-tauri/target/release/bundle/macos/*.app.tar.gz
        if-no-files-found: warn
        retention-days: 30 