name: 'Build Multi-Platform Release'

on:
  # 推送到main分支时触发，或创建tag时触发
  push:
    branches: [ main ]
    tags:
      - 'v*'
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || 'x86_64-pc-windows-msvc' }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Build the app
      run: npm run tauri:build
      env:
        # macOS 构建时设置环境变量，跳过代码签名
        APPLE_SIGNING_IDENTITY: "-"

    - name: Get app version (Windows)
      if: matrix.platform == 'windows-latest'
      shell: pwsh
      run: |
        $version = (Get-Content package.json | ConvertFrom-Json).version
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV

    - name: Get app version (macOS)
      if: matrix.platform == 'macos-latest'
      run: |
        version=$(node -pe "require('./package.json').version")
        echo "APP_VERSION=$version" >> $GITHUB_ENV

    # Windows 构建产物处理
    - name: Create Release - Windows (if tag)
      if: startsWith(github.ref, 'refs/tags/') && matrix.platform == 'windows-latest'
      uses: softprops/action-gh-release@v1
      with:
        name: "鼠标步数计数器 v${{ env.APP_VERSION }}"
        files: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows Artifacts (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.platform == 'windows-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ env.APP_VERSION }}
        path: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
          src-tauri/target/release/mouse-step-counter.exe
        if-no-files-found: warn
        retention-days: 30

    # macOS 构建产物处理
    - name: Create Release - macOS (if tag)
      if: startsWith(github.ref, 'refs/tags/') && matrix.platform == 'macos-latest'
      uses: softprops/action-gh-release@v1
      with:
        name: "鼠标步数计数器 v${{ env.APP_VERSION }}"
        files: |
          src-tauri/target/release/bundle/dmg/*.dmg
          src-tauri/target/release/bundle/macos/*.app.tar.gz
          src-tauri/target/release/bundle/macos/*.app
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS Artifacts (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.platform == 'macos-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ env.APP_VERSION }}
        path: |
          src-tauri/target/release/bundle/dmg/*.dmg
          src-tauri/target/release/bundle/macos/*.app
        if-no-files-found: warn
        retention-days: 30 