name: 'Build Windows Release'

on:
  # 推送到main分支时触发，或创建tag时触发
  push:
    branches: [ main ]
    tags:
      - 'v*'
  # 手动触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Build the app
      run: npm run tauri:build

    - name: Get app version
      shell: pwsh
      run: |
        $version = (Get-Content package.json | ConvertFrom-Json).version
        echo "APP_VERSION=$version" >> $env:GITHUB_ENV

    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: "鼠标步数计数器 v${{ env.APP_VERSION }}"
        files: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows Installer (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer-${{ env.APP_VERSION }}
        path: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
        if-no-files-found: warn
        retention-days: 30

    - name: Upload Windows Portable (if not tag)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: windows-portable-${{ env.APP_VERSION }}
        path: src-tauri/target/release/mouse-step-counter.exe
        if-no-files-found: warn
        retention-days: 30 